### ISSUE TITLE
Add “what” and “why” information to README

### ISSUE THREAD

**Issue by KirstieJane** [ohbm/OpenScienceDemoCalls#1]
We need to add a few sentences to the README file for this repository about WHAR the demo calls are and WHY we want to hold them

I know @KirstieJane is the best person to write them but she (I) am silly busy at the moment so any additional help is welcome :sparkles:

**Comment by emdupre** [comment]
Opened #3 to start to address this!

**Comment by KirstieJane** [comment]
Closed! Thank you! :sunflower:
