### ISSUE TITLE
Create questions for interviewees to fill out before demo call

### ISSUE THREAD

**Issue by emdupre** [ohbm/OpenScienceDemoCalls#10]
As mentioned by @KirstieJane, it would be great to have a small, standardized set of questions that interviewees can fill out before the demo calls. How should we go about drafting these?

**Comment by KirstieJane** [comment]
Here are some ideas to get started:

* Your name
* Name of the project
* Project website
* The problem the project is trying to solve
* What is fun about the project?
* How can someone get involved with the project?

**Comment by KirstieJane** [comment]
Oh - there should also be a question about open in there!

* In what way(s) is the project “open”? (Implicitly, what does “open” mean in this context?)

**Comment by KirstieJane** [comment]
I've hopefully covered this in #14. Any comments welcome!

**Comment by KirstieJane** [comment]
I think this is covered in the guide. @emdupre - go ahead and close this issue if it all looks good to you 😸
