### ISSUE TITLE
Create google calendar with the talks

### ISSUE THREAD

**Issue by yarikoptic** [ohbm/OpenScienceDemoCalls#11]
so ppl could easily add to their calendars and join live? (if it is happening live, otherwise ignore/close)

**Comment by KirstieJane** [comment]
It is live so can definitely make a calendar. Worth it even if there’s only one event per month?

**Comment by yarikoptic** [comment]
IMHO yes.  It is not a frequency what matters but being able to see it in (my) schedule without any additional action to do (besides once adding a calendar)

**Comment by KirstieJane** [comment]
:+1: Sounds good! I’ll make one from the Open.OHBM gmail account :smile:

**Comment by KirstieJane** [comment]
Made a calendar! Here it is: https://calendar.google.com/calendar/embed?src=open.hbm%40gmail.com

Here's the ical format: https://calendar.google.com/calendar/ical/open.hbm%40gmail.com/public/basic.ics

I'll add this to the README now 😄
