### ISSUE TITLE
Technical issues troubleshooting/protocol

### ISSUE THREAD

**Issue by adelavega** [ohbm/OpenScienceDemoCalls#19]
Thanks for having me today. Fun times! 

I thought it might be useful to discuss troubleshooting solutions with Google Hangouts and what the best protocol. This seems to be a persistent problem as I've had issues come up in the past (when giving remote presentation w/ @ccraddock)

One suggestion is for participants to check their set up prior to joining. I actually did that by getting on a Hangout call with myself and I was able to realize my microphone was muted at the system level! Phew. It did require having two Google accounts to verify this however. 

Having a phone with Hangouts as a backup might be a good thing to suggest as well, as it tends to be more reliable and sometimes the video quality is better. I would ensure to be on Wifi to avoid connectivity problems, though.

**Comment by KirstieJane** [comment]
Thank you for getting this started @adelavega! Really appreciate it!

**Comment by mvdoc** [comment]
From the viewers' side, I just want to say that the quality of the video was impressive (we were watching the call on a 4K TV and the streaming was in HD).

**Comment by KirstieJane** [comment]
Thank you @mvdoc, really good to know!

While the idea of me being in HD on a 4K TV is somewhat terrifying, I’m glad it was good quality 🤣.
