### ISSUE TITLE
Which YouTube channel should we stream from

### ISSUE THREAD

**Issue by KirstieJane** [ohbm/OpenScienceDemoCalls#2]
I can see OHBM has their [own channel](https://www.youtube.com/channel/UCwMM4wEFi_hx2_6wVVoPBJA), but I’m concerned that they won’t like us live streaming from it without previous editing??

Brainhack has a [channel](https://www.youtube.com/channel/UC7Bde2UpQphkDI4QJgldZUw) with just 1 upload, maybe we could steam from that (@ccraddock?)

Or we can make an OHBM OpenScience channel?

What do you think?

**Comment by ccraddock** [comment]
I vote for OHBM openscience channel.

**Comment by KirstieJane** [comment]
I’m good with a new YouTube channel too. I can make a new gmail account to go with it? Unless we already have one?

**Comment by mvdoc** [comment]
I think it would be nice to have a new youtube channel as well for OHBM Open Science related videos. And I don't think we have a gmail account yet (but I might be wrong ;))

**Comment by lunebellec** [comment]
There is a hbm.hackathon@gmail.com, which I have shared with Greg and Anisha.

But I don't think there is a hbm.open.science@gmail.com, and there should.

**Comment by emdupre** [comment]
.@pbellec what's the benefit of having both hbm.hackathon@gmail.com and hbm.open.science@gmail.com addresses?

I'm not sure what we use hbm.hackathon for besides directly coordinating the hackathon&mdash; if it's already overloaded with other activities, creating a new address makes sense to me! Otherwise, it might be nice to consolidate.

**Comment by satra** [comment]
perhaps we should just call it: `hbmOS@gmail.com` after all open science is like the operating system of hbm :)

**Comment by lunebellec** [comment]
the OS SIG is more than just the hackathon. I guess we could operate the hackathon using the hbmOS address (I love it Satra, btw), but it would be problematic to equate OS SIG and hackathon. 

Also, there is indeed a lot of traffic on the hackathon address, in particular when we receive applications for funding.

**Comment by gkiar** [comment]
@satra @pbellec love hbmOS as well - I think we need 6 characters (sans `.`) for google though (I wasn't allowed to get `gkiar` for this reason), so we could either do ohbm.OS@gmail.com, or theorganizationforhumanbrainmappingopensciencespecialinterestgroup@gmail.com, whichever rolls off the tongue more easily 😉

**Comment by emdupre** [comment]
+1 for OHBM.OS@gmail.com !

**Comment by jbpoline** [comment]
sounds good !
JB

**Comment by mvdoc** [comment]
👍

**Comment by chrisgorgo** [comment]
+1 for the hbmOS. Great idea.

Best,
Chris

**Comment by KirstieJane** [comment]
As per our discussion in the slack channel, our favourite option was already taken, so I've gone with `open.hbm@gmail.com`. Let me know if you'd like the password 😄

**Comment by lunebellec** [comment]
@KirstieJane under settings / accounts / grant access to another account you can share a gmail account with other people. It is cleaner than sharing the password.

**Comment by KirstieJane** [comment]
@pbellec - NICE - thank you. Let’s do that instead :sparkles:
