### ISSUE TITLE
Figure out who to invite for the March call (22nd at 7pm)

### ISSUE THREAD

**Issue by KirstieJane** [ohbm/OpenScienceDemoCalls#22]
Need to send some invites ✨

**Comment by emdupre** [comment]
We have a little more time on this issue, but it might be nice to tie back in to some of the larger initiatives discussed in the first call, like Brainhack and BIDS. Or to introduce some new ones !

What would you think of having someone on to speak about the boarder NIPY community ? Or specifically talk about a BIDS App they've developed / are developing ?

**Comment by arokem** [comment]
If you want, I'd be happy to talk about the nipy community, and the even broader context of scipy/pydata.

**Comment by emdupre** [comment]
Thanks so much, @arokem !! 🎉 I'll let @KirstieJane confirm, but I think that would be great.

**Comment by emdupre** [comment]
We've updated the date, here-- it's now planned for March 22nd (the week before !).

**Comment by arokem** [comment]
Hi! Just a heads up that I can't make the 22nd. Maybe this works with #26, though?

**Comment by emdupre** [comment]
We ended up finding three guests for this month's call. Hopefully we can get you on a future call, @arokem ! Thanks again for volunteering 😄

**Comment by arokem** [comment]
No problem. Thanks for heads-up!

I am happy to see that Eleftherios will be carrying forth the NIPY banner.

**Comment by KirstieJane** [comment]
Thanks @emdupre!

@arokem - you’re in for April’s call, right? On 26th April 😸

**Comment by arokem** [comment]
Ah yes. That confused me, but sure - I still have that on my calendar 😅

**Comment by emdupre** [comment]
Oh sorry ! I didn't realize that was settled. Sorry for the confusion 😅  Looking forward to April !

**Comment by KirstieJane** [comment]
I hadn’t told you! So sorry @emdupre!!

Thanks @arokem!! Looking forward to the story of NiPy!
