### ISSUE TITLE
Figure out who to invite for April call

### ISSUE THREAD

**Issue by KirstieJane** [ohbm/OpenScienceDemoCalls#32]
These calls just keep coming around don't they!

The April call is on **Thursday 26th April at 7pm BST**.

I think @arokem was on deck for April.

@chrisfilo also suggested Tammy to talk about https://breakspear.github.io/moviesinthemagnet/

What about advertising the OHBM hackathon? @gkiar could talk? But maybe that's not great because the travel award deadline is before this call so it might be kinda annoying to advertise but then say "oh, you missed the boat"??

@guiomar also had some good suggestions for EEG/MEG folks?

**Comment by chrisgorgo** [comment]
I would also suggest Dora Hermes who is working on BIDS iEEG (https://vistalab.stanford.edu/dora-hermes/)

**Comment by guiomar** [comment]
Yes :)
Sylvain Baillet (sylvain.baillet@mcgill.ca), Elizabeth Bock (@ebock) and François Tadel (@ftadel) could talk about  the Open MEG archives (OMEGA): https://www.mcgill.ca/bic/resources/omega and about Brainstorm: http://neuroimage.usc.edu/brainstorm/ in any of your sessions.

**Comment by gkiar** [comment]
@KirstieJane I also have other projects that may be generally of interest (i.e. https://clowdr.github.io/, https://boutiques.github.io/), but can shout out the hackathon too? That way it's not tooo much like "hey you just missed a deadline" and more like, "come join the awesome \<here\>!"

**Comment by KirstieJane** [comment]
As @emdupre updated the README to say:

> This month we'll be speaking to Dora Hermes about the iEEG BIDS extension, Christine Guo and Tammy Vanderwal about their open science naturalistic viewing competition, and Ariel Rokem about SciPy.

@guiomar: thank you for your suggestions - we haven't forgotten them I promise!

@gkiar: thank you for your offer! We'll definitley have you on sometime soon!
