### ISSUE TITLE
Draft email to send out to OHBM members

### ISSUE THREAD

**Issue by KirstieJane** [ohbm/OpenScienceDemoCalls#4]
We need a brief explanation of what the demo call is and how people can join.

Leaving this here in case anyone wants to help out (otherwise I'll do it - KW) 😄

**Comment by emdupre** [comment]
Nikola also offered to help edit this, if desired !

**Comment by KirstieJane** [comment]
Closed! Email at https://github.com/ohbm/OpenScienceDemoCalls/blob/master/comms/ohbm-democalls-ann.md
