### ISSUE TITLE
Figure out who to invite to the first demo call

### ISSUE THREAD

**Issue by KirstieJane** [ohbm/OpenScienceDemoCalls#5]
I'm thinking BIDS would be a good project to start with - @chrisfilo: would you like to talk? Or is there someone you can deputise?

**IF** Brainhack Global 2018 is happening (we might be running out of time to get it planned??) then @ccraddock maybe you could talk about that?

I also just reviewed [Porcupine](https://timvanmourik.github.io/Porcupine/) and thought that would be a good project to feature?

(That's three if those all work out)

But another option would be to pick an EEG/MEG project - someone from MNE python perhaps?

Other suggestions very welcome!

---

#### Confirmed:

* @ccraddock on Brainhack Global
* @guiomar on MEG BIDS
* @adelavega on NeuroScout

---

#### Actions

- [x] Asked Chris on slack/github. Confirmed already ✨ 
  * Update - no longer available
- [x] Sent email & slack message to Tim v M
  * Update - not available this month, ok for next month
- [x] Sent slack message to Cameron 
    * Confirmed from Cameron
- [x] Send slack message to Matteo
- [x] Sent email & slack message to Guiomar

**Comment by chrisgorgo** [comment]
I would be happy to talk, but could you remind me when is the first demo call?

**Comment by KirstieJane** [comment]
Thanks @chrisfilo! That's great.

It seems from the slack chat that I'm being forgiven for changing the date to 1st Feb. Give me a thumbs up either here or slack if that's ok with you and I'll update the README here.

**Comment by chrisgorgo** [comment]
That day works for me. What time so I could block it in my calendar?

**Comment by KirstieJane** [comment]
7pm GMT so 11am PST 🌻
