### ISSUE TITLE
Figure out who to invite for the second demo call

### ISSUE THREAD

**Issue by KirstieJane** [ohbm/OpenScienceDemoCalls#9]
Because we've pushed January's call to 1st Feb, the second call on 22nd Feb will come rather quickly after it!

Let's have a think about some people we can invite for that second call in advance so we're not behind the times 👾 

### Update! We have three guests confirmed!

* Anisha Keshavan @akeshavan 
* Yaroslav Halchenko @yarikoptic
* Athina Tzovara @aath0

**Comment by emdupre** [comment]
I'm not sure whether to suggest here or in #7 ! 

I have a couple of ideas, but one close to home would be to hear from @mvdoc about [DueCredit](https://github.com/duecredit/duecredit). It's a project that aims to increase citing of open-source software, and so improve the health of the community! Pretty cool stuff, I think 😄

**Comment by KirstieJane** [comment]
Than you @emdupre! Great choice! @mvdoc - I pinged you a message on Slack to see if you could actually speak on the first call on 1st Feb! 🤞

**Comment by KirstieJane** [comment]
@yarikoptic is in for Feb 22nd 🎉 

@akeshavan is confirmed too ✨

**Comment by KirstieJane** [comment]
And @aath0! We have a full house :tada: :balloon:

**Comment by emdupre** [comment]
Closing this, since we have three guests for the February 22nd call !
